version: '3'

services:
  stats:
    build:
      context: ./
      dockerfile: Dockerfile
    image: charityroyale/stats
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.charityroyale-stats.rule=Host(`stats.hammertime.studio`)'
      - 'traefik.http.routers.charityroyale-stats.entrypoints=websecure'
      - 'traefik.http.routers.charityroyale-stats.tls.certresolver=myresolver'
    networks:
      - internal
    restart: always

networks:
  internal:
    name: 'paddy_internal'
    external: true
